name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Build the Docker Image
      run: |
        source versions.sh
        docker build --build-arg ANSIBLE_VERSION=${ANSIBLE_IMAGE_VERSION} --build-arg BASE_IMAGE_TAG=${JENKINS_IMAGE_TAG} -f ${DOCKERFILE_PATH} -t ${DOCKER_REPO}:${ANSIBLE_IMAGE_VERSION} .
    - name: Test the Docker image
      run: |
        sh tests/run_test.sh
    - name: Test the Docker image
      run: |
        echo ${ANSIBLE_IMAGE_VERSION}
    #- name: Publish to Registry
    #  uses: elgohr/Publish-Docker-Github-Action@master
    #  with:
    #    name: myDocker/repository
    ##    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
