name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Build the Docker Image
      run: |
        source versions.sh
        docker build --build-arg ANSIBLE_VERSION=${ANSIBLE_IMAGE_VERSION} --build-arg BASE_IMAGE_TAG=${JENKINS_IMAGE_TAG} -f ${DOCKERFILE_PATH} -t ${DOCKER_REPO}:${ANSIBLE_IMAGE_VERSION} .
    - name: Test the Docker image
      run: |
        source versions.sh      
        docker tag ${DOCKER_REPO}:${ANSIBLE_IMAGE_VERSION} ${DOCKER_REPO}:sut
        cd tests
        docker-compose up
    - name: Publish to Dockerhub
      run: |
        source versions.sh    
        docker push ${DOCKER_REPO}:${ANSIBLE_IMAGE_VERSION}

