name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        source versions.sh
        docker build --build-arg ANSIBLE_VERSION=$ANSIBLE_IMAGE_VERSION --build-arg BASE_IMAGE_TAG=$JENKINS_IMAGE_TAG -f $DOCKERFILE_PATH -t $IMAGE_NAME .
        docker tag $IMAGE_NAME $DOCKER_REPO:sut

