name: Ansible Version Update

on: 
  push:
    branches:
      - production
  schedule:
    - cron:  '0 20 * * *'      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        ref: 'production'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Update Ansible Version
      run: |
        git remote set-url --push origin https://Bettysbot:${GITHUB_TOKEN}@github.com/ottenwbe/jenkins-ansible-agent
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'ottenwbe.public@gmail.com'        
        python scripts/update/update.py        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        
